### ISSUE TITLE
Handling rich push

### ISSUE THREAD

**Issue by adamlevy-emjay** [customerio/customerio-ios#176]
According to the documentation for setting up rich push notifications, the following must be called after the notification was tapped:
`let handled = MessagingPush.shared.userNotificationCenter(center, didReceive: response,
                                                                 withCompletionHandler: completionHandler)`
The problem I'm having is if I call this method then CustomerIO handles the deep link by opening it in a browser when instead I should handle the deep link myself.  If I don't call this method then the open and delivered events don't get tracked so I have to manually call trackMetric.  

If we shouldn't be calling  `let handled = MessagingPush.shared.userNotificationCenter(center, didReceive: response,
                                                                 withCompletionHandler: completionHandler)` when handling our own push then please state that in the documentation.

**Comment by ddanielczyk** [comment]
@levibostian  Question to this topic - do you provide an easy way to extract the deeplink (or other data) from push notification payload? Since you already do this internally, maybe it would be good idea to give us easy access to PushContent or just a .deeplink ? Otherwise, we have to parse the UserInfo dict manually and if it ever changes on your side, we may have a problem on app side.

**Comment by levibostian** [comment]
Great question. At this time, no, we do not provide a parsed object in the public API of the SDK. This is something that has been talked about, but never implemented. 

We do have an [object used specifically for parsing the payload](https://github.com/customerio/customerio-ios/blob/5c127e5f32a16e568f4fd969094223130de42e36/Sources/MessagingPush/PushContent.swift) the SDK uses internally. It is public it looks like if you want to use it. Although, it's undocumented which means we may change the API at anytime without a breaking change warning. 

🤔 I'll propose this idea to the team. See what we come up with in regards to this idea... Thanks for suggesting it!

**Comment by ddanielczyk** [comment]
I would really appreciate that. It's a bit unsafe to depend on string dictionary key, when retrieving the deeplink. If for any reason it changes on your side, apps will have no way to know about it.

While it is possible to use `PushContent` object, it requires a JsonAdapter at init, which requires Logger at init, which requires SdkConfig at init .. ;) You get my point, it's quite complicated to build that object, just to parse notification payload.

Thanks!

**Comment by levibostian** [comment]
Everything that we have discussed today (in this ticket and the other 2) have been documented and shared with the mobile team. Again, I greatly appreciate you sharing your thoughts and use cases with us today. Thank you, thank you!

**Comment by levibostian** [comment]
Update: Both issues addressed here have been resolved in the latest `1.2.0-alpha.2` of the SDK! 

We are working on docs but in the meantime, you can test the feature using example code [in this PR's description](https://github.com/customerio/customerio-ios/pull/177). 

The new feature allows you to handle deep links yourself instead of the SDK. We also provide to you an object with the parsed push payload so you can more easily get the deep link!
