### ISSUE TITLE
Device push_enabled attribute is not updated when notifications get disabled.

### ISSUE THREAD

**Issue by ddanielczyk** [customerio/customerio-ios#179]
Since all attributes of device are send only when a) push token changes b) app manually set custom device attribute, the `push_enabled` attribute does not represent current status of device when user disable push notifications.

If we want to have campaign where we send a push notification if it's enabled on device, otherwise send an email message - the push_enabled must always represent the most current value.

Proposed solution would be to always resend the device attributes when app is opened (even if it's coming from background).

Workaround solution I use for now is to set a new custom device attribute every time app is opened, it then triggers to re-evalue the push_enabled attribute value and send it to backend together with other attributes.

**Comment by ddanielczyk** [comment]
@levibostian  thanks for reply.

This all works as you described.

The problem is, when you close the app, go to device settings -> disable push notifications for this app, then go back to app. It won't then receive the push token and registerToken won't be called in SDK, so it won't update attribute push_enabled to false, so we won't know on the web, that user has disabled push notifications.

**Comment by levibostian** [comment]
Ah, good point. 

I am used to apps where background push notifications are enabled which allows you to get a push token even if permissions are disabled. So, I forget about this use case that you describe. 

Because our API currently relies heavily on a push token for device attributes, if there is no push token given, then it's difficult to be able to send that to our API. 

I'll pass this use case onto our product team. In the mean time, the only workaround that I can think of at this time is to enable background push notifications in the entitlements of your app.

**Comment by ddanielczyk** [comment]
Okay, that sounds like a valid workaround. Question - do you use background notifications capability for anything more than just getting device token? Is customer.io sending any background notifications ?

**Comment by levibostian** [comment]
> Is customer.io sending any background notifications?

At this time, the Customer.io backend will only send a background notification if you send one. You can construct a push payload to be in the format of a background push notification.

**Comment by ddanielczyk** [comment]
@levibostian Follow up on this - actually it was my mistake, it looks like device is getting push token every time it requests for it, even without background notification, and even when notifications are disabled by the user.
