### ISSUE TITLE
After clearIdentify() SDK still sends something to server with old identity

### ISSUE THREAD

**Issue by pirrest** [customerio/customerio-ios#218]
**SDK version:** 1.2.0-beta.4

**Environment:** Development and Production

**Describe the bug**
After calling clearIdentify() method SDK still sends some data to server.

**To Reproduce**
- identify() user via SDK - this will create new user on customer.io
- delete user manually on customer.io
- run clearIdentify() and do not exit the app
- in 10-20 seconds user will reappear on customer.io

**Expected behavior**
We are trying to build such logic in our app:
When user clicks on "Delete profile" inside our app we need to clean all the data of the user.
First I run clearIdentify()
Then I send request to our server to clean the data and our server removes user from customer.io
And I expect that user is not present on customer.io any more.
But after some time (10-20 seconds) I see that user is recreated again.
I assume that SDK on iOS making data saves in background and it looks like even after clearIdentify() was invoked it still saves (may be for the last time) some data which recreates user.

**Comment by pirrest** [comment]
Maybe this is false alarm. Checking also on our server, maybe it sends some data to customer io after user removal..

**Comment by pirrest** [comment]
Not the false alarm. I see that user is recreated from SDK. That is data that was set earlier via SDK. So it is being sent after clearIdentity().
<img width="1232" alt="Знімок екрана 2022-11-17 о 10 28 18" src="https://user-images.githubusercontent.com/1370801/202395295-af6c004a-41d2-4584-8572-97fb6d68e739.png">

**Comment by pirrest** [comment]
Or at least I need a way to know that all data was flushed to servers via SDK API or force flush it. In that way I will be sure that after clearIdentify() there will no requests to server anymore.

**Comment by levibostian** [comment]
👋 Hello there, @pirrest. Thanks for all of the details that you sent us. Very helpful. 

I am not 100% sure what is happening without seeing a full picture of all the timestamps of events that have happened in the SDK and in Customer.io. 

I recommend you turning on SDK logging and reproducing the steps above that you gave us. 

```swift
CustomerIO.initialize(siteId: "abc", apiKey: "xyz", region: Region.US) {
  $0.logLevel = .debug
}
```

`.debug` level is a little noisy. `.info` might be good enough for you. 

Our mobile SDKs use a [queue](https://customer.io/docs/sdk/ios/getting-started/#the-processing-queue) to send data to Customer.io in chunks instead of immediately. I am guessing that is what is happening is that there are HTTP calls happening in the SDK after you manually delete a profile in Customer.io. Seeing the SDK logs will give you timestamps of events which should help you determine if this is true.

**Comment by levibostian** [comment]
I am going to close this issue for now since I have not heard back. 

We have launched v2 of our SDK today. I recommend you upgrade your app to using this new version. If you still encounter a problem, feel free to come back to this issue and I'll re-open it.
