### ISSUE TITLE
Crash DIGraph_SdkConfigStore_singleton_access

### ISSUE THREAD

**Issue by alpha-khambir** [customerio/customerio-ios#222]
**SDK version:** 1.2.4

**Environment:**  Production

**Are logs available?** 
No, because we can not reproduce a crash in a debug area

**Describe the bug**
In our crashlytics we can see a lot of crashes from the customer io library.
Crash:
```
Crashed: DIGraph_SdkConfigStore_singleton_access
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
```
Now the app crashes on any screen, any user flow, we can see it in the crashlytics.

**To Reproduce**
Can not reproduce from our side

**Expected behavior**
An app should not crash.

**Screenshots**
<img width="630" alt="Screenshot 2022-11-23 at 2 52 13 PM" src="https://user-images.githubusercontent.com/93246264/203552361-fd409e0c-da52-43f2-8278-6616060bf90a.png">

[issue_ca7686a2dbc4478891e440a0b082755c_crash_session_4192f76bfb2e45a8be413c7800cba7e2_DNE_0_v2_stacktrace.txt](https://github.com/customerio/customerio-ios/files/10075663/issue_ca7686a2dbc4478891e440a0b082755c_crash_session_4192f76bfb2e45a8be413c7800cba7e2_DNE_0_v2_stacktrace.txt)

**Comment by ami-aman** [comment]
Hi @alpha-khambir @Arideno 

Thank you for flagging this issue. Can you confirm if you are using custom or creating own instances of CustomerIO iOS SDK in your app ? We have deprecated creating own instances of the SDK and using it could be a possible reason behind this issue.

**Comment by alpha-khambir** [comment]
Hi @ami-aman 
We are using shared `CustomerIO` and shared `MessagingPush`.
And also initialize CustomerIO via `initialize` method.

```
CustomerIO.initialize(
   siteId: BuildConfiguration.customerIOSiteID,
   apiKey: BuildConfiguration.customerIOAPIKey
)
```

**Comment by levibostian** [comment]
Thanks again for reporting this issue to us. The details you sent were very helpful (especially the stacktrace screenshot) to help us help you faster. 

Looking at the stacktrace, I have an idea for what the problem may be. Luckily, we just released a new version of the SDK that should hopefully fix this issue for you. 

The release is in *alpha* currently as we work to finish the final steps to get it into beta. We would love for you to try out this new release and report issues to us that you encounter. 

There are some small steps you will need to take to migrate to the new version 2 of the SDK. We plan to release those documents when we release v2 to beta. 

In the mean time, I will share this draft of the migration docs with you so you can get started with your migration and test out the release if you decide to. 

<details>
<summary>Draft of migration docs</summary>
<br>

## Upgrade from 1.x to 2.x

### Singleton API is now enforced 

In version 1.x of the Customer.io iOS SDK, could use the SDK in 2 ways:
1. Singleton API: 
```swift
CustomerIO.initialize(...) // initialize the singleton SDK instance
Customer.shared.track(...) // use the singleton SDK instance 
```

2. Non-singleton API:
```swift
let cio = CustomerIO(...) // initialize the non-singleton SDK instance
cio.track(...)            // use the non-singleton SDK instance 
```

In version 2.x, we removed the non-singleton API. To successfully migrate, you need to replace any code using a non-singleton with the singleton instance:
```swift
// Replace the non-singleton instance:
cio.track(...) 
messagingPush.application(...)
// With `CustomerIO.shared` or `MessagingPush.shared`:
CustomerIO.shared.track(...) 
MessagingPush.shared.application(...)
```

If your app uses a technique like dependency injection, you can keep your code base as-is and simply replace code where you create new instances of the SDK:
```swift
// For example, if you have code that accepts a CustomerIO dependency in the constructor (to easily allow mocking the Customer.io SDK):
class Repository {
    let customerIO: CustomerIO

    init(customerIO: CustomerIO) {
        self.customerIO = customerIO
    }
    
    func acceptFriendRequest() {
        ...
        self.customerIO.track(...)
        ...
    }
}

// You can keep your Repository as-is, but you need to change where you create instances from:
let repository = Repository(customerIO: CustomerIO(...))
repository.acceptFriendRequest()
// To:
let repository = Repository(customerIO: CustomerIO.shared) // Don't forget to initialize the SDK 😉
repository.acceptFriendRequest()
```

### Configuration of the SDK happens during SDK initialization

In version 1.x of the Customer.io iOS SDK, you configured the SDK through a `.config` function: 

```swift
CustomerIO.config {
  $0.autoTrackScreenViews = true
}
```

In version 2.x of the Customer.io iOS SDK, we moved the `.config` function into `CustomerIO.initialize`. You'll need to move your configuration into the SDK initialization process to migrate:

```swift
CustomerIO.initialize(siteId: "YOUR SITE ID", apiKey: "YOUR API KEY", region: Region.EU) { config in
  config.autoTrackScreenViews = true
}
```

Visit [the getting started doc](/docs/sdk/ios/getting-started/) to learn more about SDK configuration. 

### SDK initialization required parameters 

In version 1.x of the Customer.io SDK, the function `CustomerIO.initialize` contained optional parameters. We had to remove those and make all parameters required. 

To migrate to 2.x of the SDK, fill in the rest of the parameters in your `initialize` function: 

```swift
// v1.x
CustomerIO.initialize(siteId: "YOUR SITE ID", apiKey: "YOUR API KEY")

// v2.x
CustomerIO.initialize(siteId: "YOUR SITE ID", apiKey: "YOUR API KEY", region: Region.US) {}
// Optionally, if you want to configure settings of the SDK, do so in initialization. 
CustomerIO.initialize(siteId: "YOUR SITE ID", apiKey: "YOUR API KEY", region: Region.EU) { config in
  config.autoTrackScreenViews = true
}
```

Visit [the getting started doc](/docs/sdk/ios/getting-started/) to learn more about SDK configuration. 

### Rich push initialization 

If you have [followed our docs to setup rich push](/docs/sdk/ios/rich-push/) in your app, you should have a `Notification Service Extension` file in your code base. 

Because of the behavior of Notification Service Extensions in iOS, you need to initialize the Customer.io SDK in your host app *and in your Notification Service*. 

```swift
class NotificationService: UNNotificationServiceExtension {
   
    override func didReceive(
        _ request: UNNotificationRequest,
        withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void
    ) {
        // Make sure to initialize the SDK at the top of this function. 
        CustomerIO.initialize(siteId: "YOUR SITE ID", apiKey: "YOUR API KEY", region: Region.US) { config in
            config.autoTrackPushEvents = true 
        }
        ...
    }
}
```

See [our docs for rich push](/docs/sdk/ios/rich-push/) to learn more about rich push setup, SDK initialization, and SDK configuration. 

### Cocoapods users, make sure you have installed Firebase dependencies yourself 

The `CustomerIO/MessagingPushFCM` Cocoapod has removed all Firebase SDKs as dependencies. This means that you need to install the Firebase Cloud Messaging (FCM) dependencies in your `Podfile` on your own. 

If you installed the Customer.io SDK using Swift Package Manager, this change does not effect you. 
</details>

**Comment by alpha-khambir** [comment]
@levibostian thanks! When the new version will be released? Any estimates?

**Comment by levibostian** [comment]
@alpha-khambir No estimates at this time but hope within the next week or two. 

We upgrade `alpha` releases to `beta` once we have completed full internal testing of a release and finish documentation. Both of these tasks are underway at this moment meaning `beta` is dependent mostly on how internal testing goes.

**Comment by alpha-khambir** [comment]
@levibostian sounds good, I will wait for your release. I hope that the new version will fix this issue 🙏
