### ISSUE TITLE
Add support for live activities

### ISSUE THREAD

**Issue by AristideVB** [customerio/customerio-ios#390]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by levibostian** [comment]
Thank you for contacting us, @AristideVB. Thank you for the suggestion. 

We have live activities logged as an internal ticket for our team to prioritize. We do not details to share at this time for when a feature such as this would be shipped. 

If you are interested in sharing details about the use case that you have for live activites and why you would like them included in the SDK, the product team would love to hear from you! `product@customer.io` 

I will close this ticket since this feature is not currently on our roadmap. Feel free to share more details with us.
