### ISSUE TITLE
Add support for Swift Concurrency

### ISSUE THREAD

**Issue by dfed** [customerio/customerio-ios#548]
**Is your feature request related to a problem? Please describe.**
When turning on [Strict Concurrency checking](https://www.massicotte.org/complete-checking) in Swift, interactions with `CustomerIO` throw build errors unless I add the `@preconcurrency ` attribute to my `import CioTracking` statement.

Ideally the CustomerIO types would support Swift Concurrency, given that strict concurrency checking will be [on by default in Swift 6](https://github.com/apple/swift-evolution/blob/main/proposals/0337-support-incremental-migration-to-concurrency-checking.md#proposed-solution), and [Swift 6 is coming later this year](https://forums.swift.org/t/progress-toward-the-swift-6-language-mode/68315/33).

**Describe the solution you'd like**
Ideally, the `CustomerIO` and `CustomerIOInstance` types would be `Sendable` or `@unchecked Sendable`.

**Describe alternatives you've considered**
There are two alternatives I see:

1. Make the `CustomerIO` and `CustomerIOInstance` types `@MainActor`-bound.
2. Make customers continue to `@preconcurrency import CioTracking` or ask customers to write code like:
```
// Hack: make CustomerIO types sendable to stop the compiler from complaining.
public protocol CustomerIOSendableInstance: Sendable, CustomerIOInstance {}
extension CustomerIO: @unchecked Sendable, CustomerIOSendableInstance {}
extension CustomerIOInstanceMock: @unchecked Sendable, CustomerIOSendableInstance {}
```

**Additional context**
The sharpest edge if you decide to make your `CustomerIO` an `actor` type: [`Task`s are not guaranteed to execute in the order they are created](https://github.com/dfed/swift-async-queue#task-ordering-and-swift-concurrency). It _may_ be simpler to go the  `@unchecked Sendable` route (and ideally use locks or dispatch queues under the hood rather than ignoring the lack of thread safety).

**Comment by mrehan27** [comment]
Thank you so much for reaching out and providing all the details. This is indeed exciting, and we fully recognize the importance of your request. We've created an internal ticket to track this and are currently discussing its addition to our roadmap. However, I must clarify that it has not yet been prioritized, and unfortunately, I cannot provide a timeline at this moment. Greatly appreciate your understanding.

Since we now have an internal ticket to track this request, I will go ahead and close this issue. We'll keep this issue updated with any progress. Even after this issue is closed, please feel free to reach out if you have any more questions or have further insights to share. Your input is incredibly valuable to us. Thank you for getting in touch.

**Comment by dfed** [comment]
Understood! This isn't a quick fix, for sure.
